name: Jalankan Bot Magang Harian

on:
  schedule:
    - cron: '30 14 * * *' # Jam 21:30 WIB
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4 # Update ke v4 (Node 20+)

      - name: Set up Python
        uses: actions/setup-python@v5 # Update ke v5 (Node 20+)
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Running Script
        run: python magang.py
